/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import com.toedter.calendar.JSpinnerDateEditor;
import com.toedter.calendar.JTextFieldDateEditor;
import java.awt.Color;
import javax.swing.JFormattedTextField;
import javax.swing.JFrame;
import javax.swing.JSpinner;

/**
 *
 * @author Sanjula
 */
public class CashPayments extends javax.swing.JFrame {

    /**
     * Creates new form UnfilledGRN
     */
    private static CashPayments p;

    private CashPayments() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setBackground(new Color(100, 100, 225, 80));
        currentRadioButton.setSelected(true);

        disableDateChooser();
//        disableSpinners();
    }

    JFrame backWindow;
    int currentState;

    public synchronized static CashPayments getInstance(JFrame backWindow, int currentState) {
        if (p == null) {
            p = new CashPayments();
        }
        return p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        headingPanel = new javax.swing.JPanel();
        closeBtn = new javax.swing.JButton();
        headingLabel = new javax.swing.JLabel();
        bodyPanel = new javax.swing.JPanel();
        cheqBtn = new javax.swing.JButton();
        paidBtn = new javax.swing.JButton();
        recievedByLabel = new javax.swing.JLabel();
        lokerIdLabel = new javax.swing.JLabel();
        IssudeDateLabel = new javax.swing.JLabel();
        issuedPurposeLabel = new javax.swing.JLabel();
        grnIdTxt3 = new javax.swing.JTextField();
        amountLabel = new javax.swing.JLabel();
        recievedEmpComboBox = new javax.swing.JComboBox<>();
        issuedDateChooser = new com.toedter.calendar.JDateChooser();
        lockerComboBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        issuedDateAnotherRadioButton = new javax.swing.JRadioButton();
        issuedDateCurrentRadioButton = new javax.swing.JRadioButton();
        cashAmntValuTxf = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        reEnterAmntTxf = new javax.swing.JTextField();
        currentRadioButton = new javax.swing.JRadioButton();
        anotherRadioButton = new javax.swing.JRadioButton();
        issuedByComboBox = new javax.swing.JComboBox<>();
        issuedByLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        grnIdTxt6 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1360, 766));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));

        headingPanel.setBackground(new java.awt.Color(153, 153, 255));
        headingPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Errpng.png"))); // NOI18N
        closeBtn.setContentAreaFilled(false);
        closeBtn.setFocusable(false);
        closeBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/herror.png"))); // NOI18N
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });
        headingPanel.add(closeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 0, 40, 40));

        headingLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        headingLabel.setForeground(new java.awt.Color(255, 255, 255));
        headingLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headingLabel.setText("| CASH PAYMENTS |");
        headingPanel.add(headingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 40));

        bodyPanel.setBackground(new java.awt.Color(255, 255, 255));
        bodyPanel.setMaximumSize(new java.awt.Dimension(680, 440));
        bodyPanel.setPreferredSize(new java.awt.Dimension(680, 440));
        bodyPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cheqBtn.setBackground(new java.awt.Color(255, 255, 255));
        cheqBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cheqBtn.setText("Cheque");
        bodyPanel.add(cheqBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 210, -1));

        paidBtn.setBackground(new java.awt.Color(255, 255, 255));
        paidBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        paidBtn.setText("Paid");
        bodyPanel.add(paidBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, 210, -1));

        recievedByLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        recievedByLabel.setText("Recieved Emp :");
        bodyPanel.add(recievedByLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 140, 20));

        lokerIdLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lokerIdLabel.setText("Locker ID :");
        bodyPanel.add(lokerIdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 110, 20));

        IssudeDateLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        IssudeDateLabel.setText("Issued Date & Time :");
        bodyPanel.add(IssudeDateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 140, 20));

        issuedPurposeLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        issuedPurposeLabel.setText("Issued Purpose :");
        bodyPanel.add(issuedPurposeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 140, 20));

        grnIdTxt3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        grnIdTxt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grnIdTxt3ActionPerformed(evt);
            }
        });
        bodyPanel.add(grnIdTxt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 40, 20));

        amountLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        amountLabel.setText("Cash Amount :");
        bodyPanel.add(amountLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 110, 20));

        bodyPanel.add(recievedEmpComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 270, -1));
        bodyPanel.add(issuedDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 120, -1));

        lockerComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash" }));
        bodyPanel.add(lockerComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 270, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("min");
        bodyPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 30, 20));

        bodyPanel.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 270, -1));

        buttonGroup1.add(issuedDateAnotherRadioButton);
        issuedDateAnotherRadioButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        issuedDateAnotherRadioButton.setText("Add");
        issuedDateAnotherRadioButton.setOpaque(false);
        issuedDateAnotherRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issuedDateAnotherRadioButtonActionPerformed(evt);
            }
        });
        bodyPanel.add(issuedDateAnotherRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, -1, -1));

        buttonGroup1.add(issuedDateCurrentRadioButton);
        issuedDateCurrentRadioButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        issuedDateCurrentRadioButton.setText("Current");
        issuedDateCurrentRadioButton.setOpaque(false);
        issuedDateCurrentRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issuedDateCurrentRadioButtonActionPerformed(evt);
            }
        });
        bodyPanel.add(issuedDateCurrentRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 90, -1));

        cashAmntValuTxf.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bodyPanel.add(cashAmntValuTxf, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 270, 20));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel30.setText("Re-Enter the Amount :");
        bodyPanel.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 160, 20));

        reEnterAmntTxf.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bodyPanel.add(reEnterAmntTxf, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 270, 20));

        buttonGroup2.add(currentRadioButton);
        currentRadioButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        currentRadioButton.setText("Current");
        currentRadioButton.setOpaque(false);
        currentRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentRadioButtonActionPerformed(evt);
            }
        });
        bodyPanel.add(currentRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 80, -1));

        buttonGroup2.add(anotherRadioButton);
        anotherRadioButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        anotherRadioButton.setText("Another");
        anotherRadioButton.setOpaque(false);
        anotherRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anotherRadioButtonActionPerformed(evt);
            }
        });
        bodyPanel.add(anotherRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 200, -1, -1));

        bodyPanel.add(issuedByComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 130, -1));

        issuedByLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        issuedByLabel.setText("Issued By :");
        bodyPanel.add(issuedByLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 140, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("hh");
        bodyPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 30, 20));

        grnIdTxt6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        grnIdTxt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grnIdTxt6ActionPerformed(evt);
            }
        });
        bodyPanel.add(grnIdTxt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 40, 20));

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(headingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(headingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, -1, 410));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        this.dispose();

    }//GEN-LAST:event_closeBtnActionPerformed

    private void issuedDateAnotherRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issuedDateAnotherRadioButtonActionPerformed
        if (issuedDateAnotherRadioButton.isSelected()) {
            currentRadioBtnSelected(true);
        }
    }//GEN-LAST:event_issuedDateAnotherRadioButtonActionPerformed

    private void issuedDateCurrentRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issuedDateCurrentRadioButtonActionPerformed
        if (issuedDateCurrentRadioButton.isSelected()) {
            currentRadioBtnSelected(false);
        }
    }//GEN-LAST:event_issuedDateCurrentRadioButtonActionPerformed

    private void currentRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentRadioButtonActionPerformed
        if(currentRadioButton.isSelected()){
            issuedByComboBox.setEnabled(false);
        }
    }//GEN-LAST:event_currentRadioButtonActionPerformed

    private void anotherRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anotherRadioButtonActionPerformed
        if(currentRadioButton.isSelected()){
            issuedByComboBox.setEnabled(true);
        }
    }//GEN-LAST:event_anotherRadioButtonActionPerformed

    private void grnIdTxt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grnIdTxt3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_grnIdTxt3ActionPerformed

    private void grnIdTxt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grnIdTxt6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_grnIdTxt6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashPayments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashPayments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashPayments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashPayments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CashPayments.getInstance(null, 0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IssudeDateLabel;
    private javax.swing.JLabel amountLabel;
    private javax.swing.JRadioButton anotherRadioButton;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField cashAmntValuTxf;
    private javax.swing.JButton cheqBtn;
    private javax.swing.JButton closeBtn;
    private javax.swing.JRadioButton currentRadioButton;
    private javax.swing.JTextField grnIdTxt3;
    private javax.swing.JTextField grnIdTxt6;
    private javax.swing.JLabel headingLabel;
    private javax.swing.JPanel headingPanel;
    private javax.swing.JComboBox<String> issuedByComboBox;
    private javax.swing.JLabel issuedByLabel;
    private javax.swing.JRadioButton issuedDateAnotherRadioButton;
    private com.toedter.calendar.JDateChooser issuedDateChooser;
    private javax.swing.JRadioButton issuedDateCurrentRadioButton;
    private javax.swing.JLabel issuedPurposeLabel;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JComboBox<String> lockerComboBox;
    private javax.swing.JLabel lokerIdLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton paidBtn;
    private javax.swing.JTextField reEnterAmntTxf;
    private javax.swing.JLabel recievedByLabel;
    private javax.swing.JComboBox<String> recievedEmpComboBox;
    // End of variables declaration//GEN-END:variables

    private void disableDateChooser() {
        dateChooser1 = (JTextFieldDateEditor) issuedDateChooser.getDateEditor();
        dateChooser1.setEditable(false);

    }
    private JTextFieldDateEditor dateChooser1;

//    private void disableSpinners() {
//        spinner1 = ((JSpinner.DefaultEditor) jSpinner1.getEditor()).getTextField();
//        spinner1.setEditable(false);
//        spinner1.setBackground(Color.white);
//        spinner2 = ((JSpinner.DefaultEditor) jSpinner2.getEditor()).getTextField();
//        spinner2.setEditable(false);
//        spinner2.setBackground(Color.white);
//
//    }
//    private JFormattedTextField spinner1;
//    private JFormattedTextField spinner2;
    public void currentRadioBtnSelected(boolean b) {
        issuedDateChooser.setEnabled(b);
        grnIdTxt6.setEnabled(b);
        jLabel8.setEnabled(b);
        grnIdTxt3.setEnabled(b);
        jLabel6.setEnabled(b);
    }
}
