/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import com.toedter.calendar.JTextFieldDateEditor;
import java.awt.Color;
import javax.swing.JFrame;


public class Cheque extends javax.swing.JFrame {

    
    private static Cheque p;
    private Cheque() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setBackground(new Color(100,100,225,80));
        disableDateChooser();
    }
    JFrame backWindow;
    int currentState;
    public synchronized static Cheque getInstance(JFrame backWindow,int currentState){
        if(p==null){
            p=new Cheque();
        }
        return p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        headingPanel = new javax.swing.JPanel();
        closeBtn = new javax.swing.JButton();
        headingLabel = new javax.swing.JLabel();
        bodyPanel = new javax.swing.JPanel();
        cashBtn = new javax.swing.JButton();
        psidBtn = new javax.swing.JButton();
        recievedByLabel = new javax.swing.JLabel();
        reEnterCheqNoLabel = new javax.swing.JLabel();
        bankLabel = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        issuedDateLabel = new javax.swing.JLabel();
        validityStartDateLabel = new javax.swing.JLabel();
        amountLabel = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        issuedByLabel = new javax.swing.JLabel();
        validityLabel = new javax.swing.JLabel();
        cheqNoTxf = new javax.swing.JTextField();
        reEnterCheqNoTxf = new javax.swing.JTextField();
        bankTxf = new javax.swing.JTextField();
        amountValueTxf = new javax.swing.JTextField();
        cheqNoLabel = new javax.swing.JLabel();
        statusComboBox = new javax.swing.JComboBox<>();
        validityStartingDateChooser = new com.toedter.calendar.JDateChooser();
        issuedDateChooser = new com.toedter.calendar.JDateChooser();
        typeComboBox = new javax.swing.JComboBox<>();
        issuedByComboBox = new javax.swing.JComboBox<>();
        purposeLabel = new javax.swing.JLabel();
        purposeComboBox = new javax.swing.JComboBox<>();
        recievedByComboBox = new javax.swing.JComboBox<>();
        currentRadioButton = new javax.swing.JRadioButton();
        anotherRadioButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1360, 766));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));

        headingPanel.setBackground(new java.awt.Color(153, 153, 255));
        headingPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Errpng.png"))); // NOI18N
        closeBtn.setContentAreaFilled(false);
        closeBtn.setFocusable(false);
        closeBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/herror.png"))); // NOI18N
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });
        headingPanel.add(closeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 0, 40, 40));

        headingLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        headingLabel.setForeground(new java.awt.Color(255, 255, 255));
        headingLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headingLabel.setText("| CHEQUE PAYMENTS |");
        headingPanel.add(headingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 40));

        bodyPanel.setBackground(new java.awt.Color(255, 255, 255));
        bodyPanel.setMaximumSize(new java.awt.Dimension(680, 440));
        bodyPanel.setPreferredSize(new java.awt.Dimension(680, 440));
        bodyPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cashBtn.setBackground(new java.awt.Color(255, 255, 255));
        cashBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cashBtn.setText("Cash");
        bodyPanel.add(cashBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 210, -1));

        psidBtn.setBackground(new java.awt.Color(255, 255, 255));
        psidBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        psidBtn.setText("Paid");
        bodyPanel.add(psidBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 380, 210, -1));

        recievedByLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        recievedByLabel.setText("Recieved By :");
        bodyPanel.add(recievedByLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 140, 20));

        reEnterCheqNoLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        reEnterCheqNoLabel.setText("Re-Enter Cheque Number :");
        bodyPanel.add(reEnterCheqNoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 190, 20));

        bankLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bankLabel.setText("Bank :");
        bodyPanel.add(bankLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 110, 20));

        typeLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        typeLabel.setText("Type :");
        bodyPanel.add(typeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 110, 20));

        issuedDateLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        issuedDateLabel.setText("Issued Date :");
        bodyPanel.add(issuedDateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 110, 20));

        validityStartDateLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        validityStartDateLabel.setText("Validity Starting Date :");
        bodyPanel.add(validityStartDateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 160, 20));

        amountLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        amountLabel.setText("Amount :");
        bodyPanel.add(amountLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 140, 20));

        statusLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        statusLabel.setText("Status :");
        bodyPanel.add(statusLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 140, 20));

        issuedByLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        issuedByLabel.setText("Issued By :");
        bodyPanel.add(issuedByLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 140, 20));

        validityLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        validityLabel.setForeground(new java.awt.Color(102, 255, 0));
        validityLabel.setText("Correct");
        bodyPanel.add(validityLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, 60, 20));

        cheqNoTxf.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cheqNoTxf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cheqNoTxfActionPerformed(evt);
            }
        });
        bodyPanel.add(cheqNoTxf, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 270, 20));

        reEnterCheqNoTxf.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bodyPanel.add(reEnterCheqNoTxf, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 270, 20));

        bankTxf.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bodyPanel.add(bankTxf, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 270, -1));

        amountValueTxf.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bodyPanel.add(amountValueTxf, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 270, 20));

        cheqNoLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cheqNoLabel.setText("Cheque Number :");
        bodyPanel.add(cheqNoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 110, 20));

        bodyPanel.add(statusComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 270, -1));
        bodyPanel.add(validityStartingDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 270, -1));
        bodyPanel.add(issuedDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 270, -1));

        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash" }));
        bodyPanel.add(typeComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 270, -1));

        bodyPanel.add(issuedByComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 130, -1));

        purposeLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        purposeLabel.setText("Issued Purpose :");
        bodyPanel.add(purposeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 140, 20));

        bodyPanel.add(purposeComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 270, -1));

        bodyPanel.add(recievedByComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 270, -1));

        buttonGroup1.add(currentRadioButton);
        currentRadioButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        currentRadioButton.setText("Current");
        currentRadioButton.setOpaque(false);
        currentRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentRadioButtonActionPerformed(evt);
            }
        });
        bodyPanel.add(currentRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 80, -1));

        buttonGroup1.add(anotherRadioButton);
        anotherRadioButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        anotherRadioButton.setText("Another");
        anotherRadioButton.setOpaque(false);
        anotherRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anotherRadioButtonActionPerformed(evt);
            }
        });
        bodyPanel.add(anotherRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 80, -1));

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(headingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(headingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bodyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, -1, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        this.dispose();
      
    }//GEN-LAST:event_closeBtnActionPerformed

    private void cheqNoTxfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cheqNoTxfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cheqNoTxfActionPerformed

    private void currentRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentRadioButtonActionPerformed


    }//GEN-LAST:event_currentRadioButtonActionPerformed

    private void anotherRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anotherRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anotherRadioButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cheque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cheque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cheque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cheque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Cheque.getInstance(null,0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amountLabel;
    private javax.swing.JTextField amountValueTxf;
    private javax.swing.JRadioButton anotherRadioButton;
    private javax.swing.JLabel bankLabel;
    private javax.swing.JTextField bankTxf;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cashBtn;
    private javax.swing.JLabel cheqNoLabel;
    private javax.swing.JTextField cheqNoTxf;
    private javax.swing.JButton closeBtn;
    private javax.swing.JRadioButton currentRadioButton;
    private javax.swing.JLabel headingLabel;
    private javax.swing.JPanel headingPanel;
    private javax.swing.JComboBox<String> issuedByComboBox;
    private javax.swing.JLabel issuedByLabel;
    private com.toedter.calendar.JDateChooser issuedDateChooser;
    private javax.swing.JLabel issuedDateLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton psidBtn;
    private javax.swing.JComboBox<String> purposeComboBox;
    private javax.swing.JLabel purposeLabel;
    private javax.swing.JLabel reEnterCheqNoLabel;
    private javax.swing.JTextField reEnterCheqNoTxf;
    private javax.swing.JComboBox<String> recievedByComboBox;
    private javax.swing.JLabel recievedByLabel;
    private javax.swing.JComboBox<String> statusComboBox;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JComboBox<String> typeComboBox;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JLabel validityLabel;
    private javax.swing.JLabel validityStartDateLabel;
    private com.toedter.calendar.JDateChooser validityStartingDateChooser;
    // End of variables declaration//GEN-END:variables

    private void disableDateChooser() {
        dateChooser1 = (JTextFieldDateEditor)validityStartingDateChooser.getDateEditor();
        dateChooser1.setEditable(false);
        dateChooser2 = (JTextFieldDateEditor)issuedDateChooser.getDateEditor();
        dateChooser2.setEditable(false);
    }
    private JTextFieldDateEditor dateChooser1;
    private JTextFieldDateEditor dateChooser2;
}
