package gui;

import controller.BeforeLogout;
import db.Database;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import model.GRN_Stock;
import model.MobSystem;

/**
 *
 * @author Ravinath Geethanjana
 */
public class GRN_ViewAll extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    private static GRN_ViewAll h;

    private GRN_ViewAll() {
        initComponents();
        this.setExtendedState(GRN_ViewAll.MAXIMIZED_BOTH);
        this.setDefaultCloseOperation(GRN_ViewAll.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent we) {
                //  Home.getInstance().setVisible(true);
                GRN_ViewAll.getInstance(null, 0).dispose();
            }

        });
        dateLbl.setText(null);
        timeLbl.setText(null);
        setImgToLbl();
        setSystemDateTime();
        copywriteDate.setText(null);
        setLogoToLogoutBtn("logout");
        setLogoToHomeBtn("Home3");
        setLogUserName();
        grnIdRadioButton.setSelected(true);
    }

    JFrame backWindow;
    int currentState;

    public static synchronized GRN_ViewAll getInstance(JFrame backWindow, int currentState) {
        if (h == null) {
            h = new GRN_ViewAll();
        }
        h.grnIdRadioButton.setSelected(true);
        h.setDataToTable();
        return h;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        copywriteDate = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        grnIdRadioButton = new javax.swing.JRadioButton();
        supIdRadioButton = new javax.swing.JRadioButton();
        searchTxt = new javax.swing.JTextField();
        dateRadioButton = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        allBtn = new javax.swing.JButton();
        pendingBtn = new javax.swing.JButton();
        completedBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        deleteBtn = new javax.swing.JButton();
        viewMoreBtn = new javax.swing.JButton();
        printBtn = new javax.swing.JButton();
        grnItemsPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        grnIDLbl = new javax.swing.JLabel();
        totalAmntLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        netTotLabel = new javax.swing.JLabel();
        totDiscountLabel = new javax.swing.JLabel();
        headingPanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        imgLbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dateLbl1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        dateLbl = new javax.swing.JLabel();
        timeLbl = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        logUserNameLbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1360, 760));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(102, 153, 255));
        jPanel3.setMaximumSize(new java.awt.Dimension(1360, 50));
        jPanel3.setMinimumSize(new java.awt.Dimension(1360, 50));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("| Designed and Developed by Pirates Developers  |(Under Construnction)");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 5, -1, 20));

        copywriteDate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        copywriteDate.setForeground(new java.awt.Color(255, 255, 255));
        copywriteDate.setText("2018");
        jPanel3.add(copywriteDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 40, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 1370, 40));

        jPanel6.setMaximumSize(new java.awt.Dimension(1370, 670));
        jPanel6.setMinimumSize(new java.awt.Dimension(1370, 670));
        jPanel6.setPreferredSize(new java.awt.Dimension(1370, 670));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setMaximumSize(new java.awt.Dimension(1370, 641));
        jPanel10.setMinimumSize(new java.awt.Dimension(1370, 641));
        jPanel10.setPreferredSize(new java.awt.Dimension(1370, 641));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(grnIdRadioButton);
        grnIdRadioButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        grnIdRadioButton.setText("GRN ID");
        grnIdRadioButton.setFocusable(false);
        grnIdRadioButton.setOpaque(false);
        jPanel11.add(grnIdRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, -1, -1));

        buttonGroup1.add(supIdRadioButton);
        supIdRadioButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        supIdRadioButton.setText("Supplier ID");
        supIdRadioButton.setFocusable(false);
        supIdRadioButton.setOpaque(false);
        jPanel11.add(supIdRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, -1, -1));

        searchTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchTxtKeyReleased(evt);
            }
        });
        jPanel11.add(searchTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 360, -1));

        buttonGroup1.add(dateRadioButton);
        dateRadioButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dateRadioButton.setText("Date");
        dateRadioButton.setFocusable(false);
        dateRadioButton.setOpaque(false);
        jPanel11.add(dateRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 0));
        jLabel6.setText("Search By : ");
        jPanel11.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, 20));

        allBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        allBtn.setText("All");
        allBtn.setFocusable(false);
        allBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allBtnActionPerformed(evt);
            }
        });
        jPanel11.add(allBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 50, 80, -1));

        pendingBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pendingBtn.setText("Pending");
        pendingBtn.setFocusable(false);
        pendingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pendingBtnActionPerformed(evt);
            }
        });
        jPanel11.add(pendingBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 50, 90, -1));

        completedBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        completedBtn.setText("Completed");
        completedBtn.setFocusable(false);
        completedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completedBtnActionPerformed(evt);
            }
        });
        jPanel11.add(completedBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 50, 100, -1));

        jPanel10.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1320, 100));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "GRN ID", "Date", "Supplier ID", "Supplier Name", "Net Total", "Status"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel10.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 620, 470));

        deleteBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        deleteBtn.setText("Delete Selected");
        deleteBtn.setFocusable(false);
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        jPanel10.add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 630, 180, -1));

        viewMoreBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        viewMoreBtn.setText("Payment");
        viewMoreBtn.setFocusable(false);
        viewMoreBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewMoreBtnActionPerformed(evt);
            }
        });
        jPanel10.add(viewMoreBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 630, -1, -1));

        printBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        printBtn.setText("Print");
        printBtn.setFocusable(false);
        jPanel10.add(printBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 630, -1, -1));

        grnItemsPanel.setBackground(new java.awt.Color(255, 255, 255));
        grnItemsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "GRN Items", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        grnItemsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product Name", "Qty", "Buying Price", "Unit Discount", "Net Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setHeaderValue("Product ID");
            jTable2.getColumnModel().getColumn(1).setHeaderValue("Product Name");
            jTable2.getColumnModel().getColumn(2).setHeaderValue("Qty");
            jTable2.getColumnModel().getColumn(3).setHeaderValue("Buying Price");
            jTable2.getColumnModel().getColumn(4).setHeaderValue("Unit Discount");
            jTable2.getColumnModel().getColumn(5).setHeaderValue("Net Total");
        }

        grnItemsPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 640, 360));

        grnIDLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        grnIDLbl.setText("122");
        grnItemsPanel.add(grnIDLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 90, 20));

        totalAmntLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        totalAmntLabel.setText("1000.00");
        grnItemsPanel.add(totalAmntLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 90, 20));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("GRN ID:");
        grnItemsPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 20));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Net Total:");
        grnItemsPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, 70, 20));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Total Discount:");
        grnItemsPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, -1, 20));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Total Amount:");
        grnItemsPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 20));

        netTotLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        netTotLabel.setText("1000.00");
        grnItemsPanel.add(netTotLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, 70, 20));

        totDiscountLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        totDiscountLabel.setText("1000.00");
        grnItemsPanel.add(totDiscountLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 90, 20));

        jPanel10.add(grnItemsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 140, 680, 470));

        jPanel6.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 670));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 670));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1370, 710));

        headingPanel.setBackground(new java.awt.Color(153, 153, 255));
        headingPanel.setMaximumSize(new java.awt.Dimension(1360, 50));
        headingPanel.setMinimumSize(new java.awt.Dimension(1360, 50));
        headingPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(153, 153, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cell Corner Mobile Shop");

        dateLbl1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dateLbl1.setForeground(new java.awt.Color(255, 255, 255));
        dateLbl1.setText("No 255/b,Thalangama South,Battaramulla");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(imgLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 30, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateLbl1)
                .addGap(0, 11, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(imgLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        headingPanel.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, -1));

        jPanel7.setBackground(new java.awt.Color(153, 153, 255));

        dateLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dateLbl.setForeground(new java.awt.Color(0, 0, 102));
        dateLbl.setText("2018.12.31");

        timeLbl.setFont(new java.awt.Font("DS-Digital", 1, 14)); // NOI18N
        timeLbl.setForeground(new java.awt.Color(0, 0, 102));
        timeLbl.setText("10:26:45 AM");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(dateLbl)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(timeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dateLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        headingPanel.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 0, 140, 50));

        logoutBtn.setBorderPainted(false);
        logoutBtn.setContentAreaFilled(false);
        logoutBtn.setFocusPainted(false);
        logoutBtn.setFocusable(false);
        logoutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutBtnMouseExited(evt);
            }
        });
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });
        headingPanel.add(logoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 10, 30, 30));

        homeBtn.setBorderPainted(false);
        homeBtn.setContentAreaFilled(false);
        homeBtn.setFocusPainted(false);
        homeBtn.setFocusable(false);
        homeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeBtnMouseExited(evt);
            }
        });
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        headingPanel.add(homeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 10, 30, 30));

        jPanel8.setBackground(new java.awt.Color(153, 153, 255));
        jPanel8.setForeground(new java.awt.Color(0, 0, 102));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("LOG USER :");

        logUserNameLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        logUserNameLbl.setForeground(new java.awt.Color(0, 0, 102));
        logUserNameLbl.setText("Sanjula Dilky");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logUserNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logUserNameLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        headingPanel.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 0, 250, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("| GRN DETAILS |");
        headingPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, -1, -1));

        getContentPane().add(headingPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        int i = JOptionPane.showConfirmDialog(this, "Are you Sure", "Warnig", JOptionPane.WARNING_MESSAGE);
        if (i == JOptionPane.YES_OPTION) {

            BeforeLogout b = BeforeLogout.getInstance();
            int x = b.checkSystemCurrentState();
            if (x == BeforeLogout.READY_TO_LOGOUT) {
                this.dispose();
                Home.getInstance(null, 0).dispose();
                new Thread() {
                    @Override
                    public void run() {
                        try {
                            Login.getInstance().setVisible(true);
                            ShutDownSystem.getInstance(1).setVisible(true);
                            Thread.sleep(1000);
                            DBConfiguration.getInstance().backupDb();
                            //System.exit(0);
                            DBConfiguration.getInstance().backupDb();
                            MobSystem.logoutSystem();

                        } catch (Exception e) {
                            e.printStackTrace();
                        }
                    }

                }.start();
                Login.getInstance().setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Cannot Logout", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void logoutBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseEntered
        setLogoToLogoutBtn("logout1");
    }//GEN-LAST:event_logoutBtnMouseEntered

    private void logoutBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseExited
        setLogoToLogoutBtn("logout");
    }//GEN-LAST:event_logoutBtnMouseExited

    private void homeBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseEntered
        setLogoToHomeBtn("Home1");
    }//GEN-LAST:event_homeBtnMouseEntered

    private void homeBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseExited
        setLogoToHomeBtn("Home3");
    }//GEN-LAST:event_homeBtnMouseExited

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        this.dispose();
        Home.getInstance(null, 0).setVisible(true);
    }//GEN-LAST:event_homeBtnActionPerformed

    private void allBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allBtnActionPerformed
        setDataToTable();
    }//GEN-LAST:event_allBtnActionPerformed

    private void pendingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pendingBtnActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        DefaultTableModel dtm2 = (DefaultTableModel) jTable2.getModel();
        try {
            String sql = "select g.grn_id as id,g.enter_date as date, s.sup_id as sup, s.company_name as supName,g.total_amount as amount,g.total_discount as discount, g.status as status from grn g inner join supplier s on s.sup_id = g.sup_id where g.status = '" + model.GRN.PENDING + "'";
            ResultSet rs = Database.search(sql);
            dtm.setRowCount(0);
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString("id"));
                v.add(rs.getString("date"));
                v.add(rs.getString("sup"));
                v.add(rs.getString("supName"));
                double ttl = Double.parseDouble(rs.getString("amount"));
                double dis = Double.parseDouble(rs.getString("discount"));
                v.add(ttl - dis + "");
                String status = "PENDING";
                if (Integer.parseInt(rs.getString("status")) == model.GRN.COMPLETE) {
                    status = "COMPLETED";
                }
                v.add(status);
                dtm.addRow(v);
                dtm2.setRowCount(0);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_pendingBtnActionPerformed

    private void viewMoreBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewMoreBtnActionPerformed
        try {
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            
            int selectedRow = jTable1.getSelectedRow();
            if(selectedRow >= 0){
                String grnID = dtm.getValueAt(selectedRow, 0).toString();
                GrnPayment.getInstance(Integer.parseInt(grnID)).setVisible(true);
            }else{
                JOptionPane.showMessageDialog(this, "Please select grn first ", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }catch(NullPointerException ex){
            JOptionPane.showMessageDialog(this, "Please select grn first ", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        catch(ArrayIndexOutOfBoundsException ex){
            JOptionPane.showMessageDialog(this, "Please select grn first ", "ERROR", JOptionPane.ERROR_MESSAGE);
        } 
        catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_viewMoreBtnActionPerformed

    private void searchTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTxtKeyReleased
        String val = searchTxt.getText().trim();
        if (!val.isEmpty()) {
            String sql = "select g.grn_id as id,g.enter_date as date, s.sup_id as sup, s.company_name as supName,g.total_amount as amount,g.total_discount as discount, g.status as status from grn g inner join supplier s on s.sup_id = g.sup_id where g.status != '" + model.GRN.DEACTIVATE + "'";
            String type = "";

            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);

            if (grnIdRadioButton.isSelected()) {
                type = "g.grn_id";
                sql += " and " + type + " like '%" + val + "%'";
            } else if (supIdRadioButton.isSelected()) {
                type = "g.sup_id";
                sql += " and " + type + " like '%" + val + "%'";
            } else if (dateRadioButton.isSelected()) {
                sql += " and g.enter_date like '" + val + "'";
            }
            try {
                ResultSet rs = Database.search(sql);
                while (rs.next()) {
                    Vector v = new Vector();
                    v.add(rs.getString("id"));
                    v.add(rs.getString("date"));
                    v.add(rs.getString("sup"));
                    v.add(rs.getString("supName"));
                    double ttl = Double.parseDouble(rs.getString("amount"));
                    double dis = Double.parseDouble(rs.getString("discount"));
                    v.add(ttl - dis + "");
                    String status = "PENDING";
                    if (rs.getString("status").equals(model.GRN.COMPLETE)) {
                        status = "COMPLETED";
                    }
                    v.add(status);
                    dtm.addRow(v);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            setDataToTable();
        }
    }//GEN-LAST:event_searchTxtKeyReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        setDataToGrnStockTbl();
    }//GEN-LAST:event_jTable1MouseClicked

    private void completedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completedBtnActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        DefaultTableModel dtm2 = (DefaultTableModel) jTable2.getModel();
        try {
            String sql = "select g.grn_id as id,g.enter_date as date, s.sup_id as sup, s.company_name as supName,g.total_amount as amount,g.total_discount as discount, g.status as status from grn g inner join supplier s on s.sup_id = g.sup_id where g.status = '" + model.GRN.COMPLETE + "'";
            ResultSet rs = Database.search(sql);
            dtm.setRowCount(0);
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString("id"));
                v.add(rs.getString("date"));
                v.add(rs.getString("sup"));
                v.add(rs.getString("supName"));
                double ttl = Double.parseDouble(rs.getString("amount"));
                double dis = Double.parseDouble(rs.getString("discount"));
                v.add(ttl - dis + "");
                String status = "PENDING";
                if (Integer.parseInt(rs.getString("status")) == model.GRN.COMPLETE) {
                    status = "COMPLETED";
                }
                v.add(status);
                dtm.addRow(v);
                dtm2.setRowCount(0);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_completedBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        DefaultTableModel dtm2 = (DefaultTableModel) jTable2.getModel();
        try {
            int selectedRow = jTable1.getSelectedRow();
            if (selectedRow >= 0) {
                String grnID = dtm.getValueAt(selectedRow, 0).toString();
                String status = dtm.getValueAt(selectedRow, 5).toString();
                int check = JOptionPane.showConfirmDialog(this, "Do you really want to delete this GRN", "Warning", JOptionPane.YES_NO_OPTION);
                if (check == JOptionPane.YES_OPTION) {
                    if (!status.equals("COMPLETED")) {
                        int i = Database.iud("update grn set status='" + model.GRN.DEACTIVATE + "' where grn_id='" + grnID + "'");
                        if (i == 1) {
                            dtm2.setRowCount(0);
                            setDataToTable();
                            JOptionPane.showMessageDialog(this, "GRN Deleted Succussfully..", "ALERT", JOptionPane.INFORMATION_MESSAGE);
                        } else {
                            JOptionPane.showMessageDialog(this, "Delete Faliuer", "ERROR", JOptionPane.ERROR_MESSAGE);
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "This GRN is already approved..You cant delete it", "ERROR", JOptionPane.ERROR_MESSAGE);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Please select a row from above Table", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(this, "Please select a row from above Table", "ERROR", JOptionPane.ERROR_MESSAGE);
        } catch (ArrayIndexOutOfBoundsException ex) {
            JOptionPane.showMessageDialog(this, "Please select a row from above Table", "ERROR", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GRN_ViewAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GRN_ViewAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GRN_ViewAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GRN_ViewAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GRN_ViewAll.getInstance(null, 0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton allBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton completedBtn;
    private javax.swing.JLabel copywriteDate;
    private javax.swing.JLabel dateLbl;
    private javax.swing.JLabel dateLbl1;
    private javax.swing.JRadioButton dateRadioButton;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel grnIDLbl;
    private javax.swing.JRadioButton grnIdRadioButton;
    private javax.swing.JPanel grnItemsPanel;
    private javax.swing.JPanel headingPanel;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel imgLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel logUserNameLbl;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JLabel netTotLabel;
    private javax.swing.JButton pendingBtn;
    private javax.swing.JButton printBtn;
    private javax.swing.JTextField searchTxt;
    private javax.swing.JRadioButton supIdRadioButton;
    private javax.swing.JLabel timeLbl;
    private javax.swing.JLabel totDiscountLabel;
    private javax.swing.JLabel totalAmntLabel;
    private javax.swing.JButton viewMoreBtn;
    // End of variables declaration//GEN-END:variables

    private void setImgToLbl() {
        try {
            Image i = new ImageIcon(getClass().getResource("/Resources/icon.png")).getImage().getScaledInstance(imgLbl.getWidth(), imgLbl.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(i);
            imgLbl.setIcon(icon);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void setSystemDateTime() {
        Timer t = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                Date d1 = new Date();
                Date d2 = new Date();
                Date d3 = new Date();
                SimpleDateFormat sdf1 = new SimpleDateFormat("yyyy-MM-dd");
                SimpleDateFormat sdf2 = new SimpleDateFormat("hh:mm:ss a");
                SimpleDateFormat sdf3 = new SimpleDateFormat("yyyy");
                String f1 = sdf1.format(d1);
                String f2 = sdf2.format(d2);
                String f3 = sdf3.format(d3);
                dateLbl.setText(f1);
                timeLbl.setText(f2);
                copywriteDate.setText(f3);
            }
        });
        t.start();
    }

    private void setLogoToLogoutBtn(String s) {
        try {
            Image i = new ImageIcon(getClass().getResource("/Resources/" + s + ".png")).getImage().getScaledInstance(logoutBtn.getWidth(), logoutBtn.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(i);
            logoutBtn.setIcon(icon);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void setLogoToHomeBtn(String s) {
        try {
            Image i = new ImageIcon(getClass().getResource("/Resources/" + s + ".png")).getImage().getScaledInstance(homeBtn.getWidth(), homeBtn.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(i);
            homeBtn.setIcon(icon);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void setLogUserName() {
        try {
            logUserNameLbl.setText("Ravinath Perera");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void setDataToTable() {
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
        try {
            String sql = "select g.grn_id as id,g.enter_date as date, s.sup_id as sup, s.company_name as supName,g.total_amount as amount,g.total_discount as discount, g.status as status from grn g inner join supplier s on s.sup_id = g.sup_id where g.status != '" + model.GRN.DEACTIVATE + "'";
            ResultSet rs = Database.search(sql);
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString("id"));
                v.add(rs.getString("date"));
                v.add(rs.getString("sup"));
                v.add(rs.getString("supName"));
                double ttl = Double.parseDouble(rs.getString("amount"));
                double dis = Double.parseDouble(rs.getString("discount"));
                v.add(ttl - dis + "");
                String status = "PENDING";
                if (Integer.parseInt(rs.getString("status")) == model.GRN.COMPLETE) {
                    status = "COMPLETED";
                }
                v.add(status);
                dtm.addRow(v);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void setDataToGrnStockTbl() {
        DefaultTableModel dtm1 = (DefaultTableModel) jTable1.getModel();
        DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
        try {
            int selectedRow = jTable1.getSelectedRow();
            if (selectedRow >= 0) {
                String grnId = dtm1.getValueAt(selectedRow, 0).toString();
                String sql = "select gs.product_pro_id as proId ,p.name as proName, gs.qty as qty, gs.get_unit_price as price, gs.unit_discount as discount from grn_stock gs inner join product p on p.pro_id = gs.product_pro_id where gs.grn_id = '" + grnId + "' and gs.status !='" + GRN_Stock.OUT_OF_STOCK + "'";
                ResultSet rs = Database.search(sql);
                dtm.setRowCount(0);
                while (rs.next()) {
                    Vector v = new Vector();
                    v.add(rs.getString("proID"));
                    v.add(rs.getString("proName"));
                    v.add(rs.getString("qty"));
                    v.add(rs.getString("price"));
                    v.add(rs.getString("discount"));
                    double ttl = (Double.parseDouble(rs.getString("qty")) * Double.parseDouble(rs.getString("price"))) - Double.parseDouble(rs.getString("qty")) * Double.parseDouble(rs.getString("discount"));
                    v.add(ttl);
                    dtm.addRow(v);
                }
                grnIDLbl.setText(grnId);
                netTotLabel.setText(dtm1.getValueAt(selectedRow, 4).toString());
                double total = 0;
                double discount = 0;
                for (int i = 0; i < dtm.getRowCount(); i++) {
                    discount += Double.parseDouble(dtm.getValueAt(i, 4).toString()) * Double.parseDouble(dtm.getValueAt(i, 2).toString());
                    total += Double.parseDouble(dtm.getValueAt(i, 3).toString()) * Double.parseDouble(dtm.getValueAt(i, 2).toString());
                }
                totDiscountLabel.setText("" + discount);
                totalAmntLabel.setText("" + total);
            } else {

            }
        } catch (NullPointerException ex) {

        } catch (ArrayIndexOutOfBoundsException ex) {

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
