/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import com.jtattoo.plaf.AbstractBorderFactory;
import com.jtattoo.plaf.AbstractIconFactory;
import com.jtattoo.plaf.AbstractLookAndFeel;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import static javax.swing.JFrame.setDefaultLookAndFeelDecorated;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import org.jvnet.substance.skin.SubstanceBusinessBlueSteelLookAndFeel;

/**
 *
 * @author Ravinath Geethanjana
 */
public class SplashScreen extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    private static SplashScreen h;

    private SplashScreen() {
        initComponents();
        setImgToBackImg();
        mainPanel.setBackground(new Color(70, 0, 255, 100));
        DeveloperPanel.setBackground(new Color(70, 0, 255, 50));
        this.setBackground(new Color(0, 0, 0, 0));
        startProgBar();
    }

    public static synchronized SplashScreen getInstance() {
        if (h == null) {
            h = new SplashScreen();
        }
        return h;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        DeveloperPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        logoLbl = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        searchNameLbl = new javax.swing.JLabel();
        pesentageLbl = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        progPanel = new javax.swing.JPanel();
        progValPanel = new javax.swing.JPanel();
        backgroundImgLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 51), 3));

        mainPanel.setBackground(new java.awt.Color(0, 102, 255));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CELL CORNER MOBILE SHOP");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("POS System Version 0.1");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Designing and Developed by Pirates Developers");

        javax.swing.GroupLayout DeveloperPanelLayout = new javax.swing.GroupLayout(DeveloperPanel);
        DeveloperPanel.setLayout(DeveloperPanelLayout);
        DeveloperPanelLayout.setHorizontalGroup(
            DeveloperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeveloperPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(DeveloperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DeveloperPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addComponent(jLabel4))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        DeveloperPanelLayout.setVerticalGroup(
            DeveloperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeveloperPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DeveloperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(DeveloperPanelLayout.createSequentialGroup()
                        .addGroup(DeveloperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        mainPanel.add(DeveloperPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 70));
        mainPanel.add(logoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 200, 180));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Welcome to CELL CORNER Mobile Shop");
        mainPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        searchNameLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        searchNameLbl.setForeground(new java.awt.Color(255, 255, 255));
        searchNameLbl.setText("Jasper");
        mainPanel.add(searchNameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 290, -1));

        pesentageLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pesentageLbl.setForeground(new java.awt.Color(255, 255, 255));
        pesentageLbl.setText("100%");
        mainPanel.add(pesentageLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, 50, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Searching :");
        mainPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        progPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));

        progValPanel.setBackground(new java.awt.Color(0, 0, 102));
        progValPanel.setPreferredSize(new java.awt.Dimension(0, 36));

        javax.swing.GroupLayout progValPanelLayout = new javax.swing.GroupLayout(progValPanel);
        progValPanel.setLayout(progValPanelLayout);
        progValPanelLayout.setHorizontalGroup(
            progValPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        progValPanelLayout.setVerticalGroup(
            progValPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout progPanelLayout = new javax.swing.GroupLayout(progPanel);
        progPanel.setLayout(progPanelLayout);
        progPanelLayout.setHorizontalGroup(
            progPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(progPanelLayout.createSequentialGroup()
                .addComponent(progValPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 498, Short.MAX_VALUE))
        );
        progPanelLayout.setVerticalGroup(
            progPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(progValPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
        );

        mainPanel.add(progPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 500, 20));
        mainPanel.add(backgroundImgLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(-8, -3, 590, 430));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                try {
                    setDefaultLookAndFeelDecorated(true);
                    UIManager.setLookAndFeel(new AbstractLookAndFeel() {
                        @Override
                        public AbstractBorderFactory getBorderFactory() {
                            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                        }

                        @Override
                        public AbstractIconFactory getIconFactory() {
                            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                        }
                    });
                } catch (Exception e) {
                }
                SplashScreen.getInstance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DeveloperPanel;
    private javax.swing.JLabel backgroundImgLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logoLbl;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel pesentageLbl;
    private javax.swing.JPanel progPanel;
    private javax.swing.JPanel progValPanel;
    private javax.swing.JLabel searchNameLbl;
    // End of variables declaration//GEN-END:variables

    private void setImgToBackImg() {
        try {
            Image i1 = new ImageIcon(getClass().getResource("/Resources/loginBackground.jpg")).getImage().getScaledInstance(backgroundImgLbl.getWidth(), backgroundImgLbl.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon icon1 = new ImageIcon(i1);
            backgroundImgLbl.setIcon(icon1);

            Image i = new ImageIcon(getClass().getResource("/Resources/icon.png")).getImage().getScaledInstance(logoLbl.getWidth(), logoLbl.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(i);
            logoLbl.setIcon(icon);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void startProgBar() {
        progValPanel.setSize(0, progValPanel.getHeight());
        progValPanel.repaint();
        progValPanel.revalidate();
        progPanel.repaint();
        progPanel.revalidate();
        new Thread() {
            @Override
            public void run() {
                for (int i = 0; i < progPanel.getWidth() - 1; i++) {
                    if (progValPanel.getWidth() == progPanel.getWidth() - 3) {
                        pesentageLbl.setText("100%");
                        // progValPanel.setSize(progPanel.getWidth() - 1, progValPanel.getHeight());
                        dispose();
                        Login.getInstance().setVisible(true);
                        break;
                    }
                    if (progValPanel.getWidth() == 100) {
                        //DB File
                        if (!checkDBFile()) {
                            break;
                        }
                    }
                    if (progValPanel.getWidth() == 200) {
                        //Config
                        if (!checkConfig()) {
                            break;
                        }
                    }
                    if (progValPanel.getWidth() == 300) {
                        //jasper
                        if (!checkJasper()) {
                            break;
                        }
                    }
                    if (progValPanel.getWidth() == 400) {
                        //DB Connection
                        if (!checkDBConn()) {
                            break;
                        }
                    }
                    try {
                        progValPanel.setSize(i, progValPanel.getHeight());
                        //pesentageLbl.setText(progValPanel.getWidth()/5+"%");
                        if (progValPanel.getWidth() % 5 >= 1 && progValPanel.getWidth() % 5 <= 4) {
                            //pesentageLbl.setText(pesentageLbl.getText());
                        } else {
                            //pesentageLbl.setText(progValPanel.getWidth() / 5 + "%");
                        }
                        Thread.sleep(5);

                    } catch (InterruptedException ex) {
                        Logger.getLogger(SplashScreen.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }

                // System.exit(0);
            }

            private boolean checkDBFile() {
                searchNameLbl.setText("Database Config file-");
                try {
                    String filelist[] = new String[]{
                        "dbName.mobsys",
                        "default.mobsys",
                        "host.mobsys",
                        "port.mobsys",
                        "pwd.mobsys",
                        "user.mobsys",
                        
                    };
                    String path = "C:/MOBSYS/db/detail/";
                    for (String file : filelist) {

                        File f = new File(path + file);
                        if (!f.exists()) {
                            JOptionPane.showMessageDialog(null, file + " Not Found");
                            return false;
                        }

                    }
                    return true;
                } catch (Exception e) {
                    return false;
                }
            }

            private boolean checkJasper() {
                searchNameLbl.setText("Jasper file-");
                return true;
            }

            private boolean checkConfig() {
                searchNameLbl.setText("System Config file-");
                return true;
            }

            private boolean checkDBConn() {
                searchNameLbl.setText("Connection Checkup");
                return true;
            }

        }.start();
    }
}
