/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import com.toedter.calendar.JTextFieldDateEditor;
import java.awt.Color;
import javax.swing.JFrame;

/**
 *
 * @author Sanjula
 */
public class ViewMore_View extends javax.swing.JFrame {

    /**
     * Creates new form UnfilledGRN
     */
    private static ViewMore_View p;

    private ViewMore_View() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setBackground(new Color(100, 100, 225, 80));

    }
    JFrame backWindow;
    int currentState;

    public synchronized static ViewMore_View getInstance(JFrame backWindow, int currentState) {
        if (p == null) {
            p = new ViewMore_View();
        }
        return p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        headingPanel = new javax.swing.JPanel();
        headingLabel = new javax.swing.JLabel();
        closeBtn = new javax.swing.JButton();
        bodyPanel = new javax.swing.JPanel();
        editBtn = new javax.swing.JButton();
        statusLabel = new javax.swing.JLabel();
        actualPayDateLabel = new javax.swing.JLabel();
        grnIdLabel = new javax.swing.JLabel();
        grnIdValueLabel = new javax.swing.JLabel();
        actualPayDateValueLabel = new javax.swing.JLabel();
        statusValueLabel = new javax.swing.JLabel();
        chequeRadioBtn = new javax.swing.JRadioButton();
        cashRadioBtn = new javax.swing.JRadioButton();
        chequeCashRadioBtn = new javax.swing.JRadioButton();
        payTypeLabel = new javax.swing.JLabel();
        chequePayPanel = new javax.swing.JPanel();
        chequeTable = new javax.swing.JScrollPane();
        chequePayTable = new javax.swing.JTable();
        chqReturnLabel = new javax.swing.JLabel();
        cashPayPanel = new javax.swing.JPanel();
        cashTable = new javax.swing.JScrollPane();
        cashPayTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1360, 766));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));

        headingPanel.setBackground(new java.awt.Color(153, 153, 255));
        headingPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headingLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        headingLabel.setForeground(new java.awt.Color(255, 255, 255));
        headingLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headingLabel.setText("| INSTALLMENT DETAILS |");
        headingPanel.add(headingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 40));

        closeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Errpng.png"))); // NOI18N
        closeBtn.setContentAreaFilled(false);
        closeBtn.setFocusable(false);
        closeBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/herror.png"))); // NOI18N
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });
        headingPanel.add(closeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 0, 40, 40));

        bodyPanel.setBackground(new java.awt.Color(255, 255, 255));
        bodyPanel.setMaximumSize(new java.awt.Dimension(680, 440));
        bodyPanel.setPreferredSize(new java.awt.Dimension(680, 440));
        bodyPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        editBtn.setBackground(new java.awt.Color(255, 255, 255));
        editBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        editBtn.setText("Edit");
        editBtn.setFocusable(false);
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });
        bodyPanel.add(editBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 20, 100, -1));

        statusLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        statusLabel.setText("Status :");
        bodyPanel.add(statusLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 50, 20));

        actualPayDateLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        actualPayDateLabel.setText("Actual Payment Date  :");
        bodyPanel.add(actualPayDateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 150, 20));

        grnIdLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        grnIdLabel.setText("GRN ID :");
        bodyPanel.add(grnIdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, 20));

        grnIdValueLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        grnIdValueLabel.setText("0001");
        bodyPanel.add(grnIdValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 80, 20));

        actualPayDateValueLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        actualPayDateValueLabel.setText("2019/03/02");
        bodyPanel.add(actualPayDateValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 110, 20));

        statusValueLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        statusValueLabel.setForeground(new java.awt.Color(153, 255, 102));
        statusValueLabel.setText("Completed");
        bodyPanel.add(statusValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 130, 20));

        buttonGroup1.add(chequeRadioBtn);
        chequeRadioBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chequeRadioBtn.setText("Cheque");
        chequeRadioBtn.setFocusable(false);
        chequeRadioBtn.setOpaque(false);
        chequeRadioBtn.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chequeRadioBtnStateChanged(evt);
            }
        });
        chequeRadioBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chequeRadioBtnMouseClicked(evt);
            }
        });
        chequeRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chequeRadioBtnActionPerformed(evt);
            }
        });
        bodyPanel.add(chequeRadioBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 20, 90, -1));

        buttonGroup1.add(cashRadioBtn);
        cashRadioBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cashRadioBtn.setText("Cash");
        cashRadioBtn.setFocusable(false);
        cashRadioBtn.setOpaque(false);
        cashRadioBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cashRadioBtnMouseClicked(evt);
            }
        });
        bodyPanel.add(cashRadioBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, -1, -1));

        buttonGroup1.add(chequeCashRadioBtn);
        chequeCashRadioBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chequeCashRadioBtn.setText("Cheque & Cash");
        chequeCashRadioBtn.setFocusable(false);
        chequeCashRadioBtn.setOpaque(false);
        chequeCashRadioBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chequeCashRadioBtnMouseClicked(evt);
            }
        });
        bodyPanel.add(chequeCashRadioBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 20, -1, -1));

        payTypeLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        payTypeLabel.setText("Payment Type :");
        bodyPanel.add(payTypeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, 110, 20));

        chequePayPanel.setBackground(new java.awt.Color(255, 255, 255));
        chequePayPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Cheque Payments", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        chequePayPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chequePayTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Check ID", "Cheque Number", "Bank", "Type", "Issued Date", "Validity Starting Date", "Amount", "Status", "Issued Emp", "Recieved Emp"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, false, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        chequePayTable.getTableHeader().setReorderingAllowed(false);
        chequeTable.setViewportView(chequePayTable);
        if (chequePayTable.getColumnModel().getColumnCount() > 0) {
            chequePayTable.getColumnModel().getColumn(0).setResizable(false);
            chequePayTable.getColumnModel().getColumn(0).setPreferredWidth(75);
            chequePayTable.getColumnModel().getColumn(1).setPreferredWidth(110);
            chequePayTable.getColumnModel().getColumn(2).setResizable(false);
            chequePayTable.getColumnModel().getColumn(3).setResizable(false);
            chequePayTable.getColumnModel().getColumn(3).setPreferredWidth(75);
            chequePayTable.getColumnModel().getColumn(4).setResizable(false);
            chequePayTable.getColumnModel().getColumn(5).setPreferredWidth(100);
        }

        chequePayPanel.add(chequeTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 1130, 180));

        chqReturnLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chqReturnLabel.setForeground(new java.awt.Color(255, 153, 153));
        chqReturnLabel.setText("Cheque Return Reason");
        chequePayPanel.add(chqReturnLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 420, 20));

        bodyPanel.add(chequePayPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 1170, 260));

        cashPayPanel.setBackground(new java.awt.Color(255, 255, 255));
        cashPayPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Cash Payments", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        cashPayPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cashPayTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cash Amount", "Locker ID", "Issued Date", "Issued Time", "Issued Emp"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cashPayTable.getTableHeader().setReorderingAllowed(false);
        cashTable.setViewportView(cashPayTable);
        if (cashPayTable.getColumnModel().getColumnCount() > 0) {
            cashPayTable.getColumnModel().getColumn(0).setResizable(false);
            cashPayTable.getColumnModel().getColumn(0).setPreferredWidth(75);
            cashPayTable.getColumnModel().getColumn(1).setPreferredWidth(110);
            cashPayTable.getColumnModel().getColumn(2).setResizable(false);
            cashPayTable.getColumnModel().getColumn(3).setResizable(false);
            cashPayTable.getColumnModel().getColumn(3).setPreferredWidth(75);
            cashPayTable.getColumnModel().getColumn(4).setResizable(false);
        }

        cashPayPanel.add(cashTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1130, 170));

        bodyPanel.add(cashPayPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 1170, 220));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(headingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bodyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(headingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 1210, 640));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        this.dispose();

    }//GEN-LAST:event_closeBtnActionPerformed

    private void chequeRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chequeRadioBtnActionPerformed

    }//GEN-LAST:event_chequeRadioBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        EditDetails e = EditDetails.getInstance(null, 0);
        e.setVisible(true);
    }//GEN-LAST:event_editBtnActionPerformed

    private void chequeRadioBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chequeRadioBtnMouseClicked
        if (chequeRadioBtn.isSelected()) {
            cashPayPanel.setEnabled(false);
            cashPayTable.setEnabled(false);
            chequePayPanel.setEnabled(true);
            chequePayTable.setEnabled(true);
            chqReturnLabel.setEnabled(true);
        }
    }//GEN-LAST:event_chequeRadioBtnMouseClicked

    private void chequeRadioBtnStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chequeRadioBtnStateChanged

    }//GEN-LAST:event_chequeRadioBtnStateChanged

    private void cashRadioBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cashRadioBtnMouseClicked
        if (cashRadioBtn.isSelected()) {
            chequePayPanel.setEnabled(false);
            chequePayTable.setEnabled(false);
            chqReturnLabel.setEnabled(false);
            cashPayPanel.setEnabled(true);
            cashPayTable.setEnabled(true);
        }
    }//GEN-LAST:event_cashRadioBtnMouseClicked

    private void chequeCashRadioBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chequeCashRadioBtnMouseClicked
        if (chequeCashRadioBtn.isSelected()) {
            chequePayPanel.setEnabled(true);
            chequePayTable.setEnabled(true);
            chqReturnLabel.setEnabled(true);
            cashPayPanel.setEnabled(true);
            cashPayTable.setEnabled(true);
        }
    }//GEN-LAST:event_chequeCashRadioBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewMore_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewMore_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewMore_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewMore_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ViewMore_View.getInstance(null, 0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actualPayDateLabel;
    private javax.swing.JLabel actualPayDateValueLabel;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel cashPayPanel;
    private javax.swing.JTable cashPayTable;
    private javax.swing.JRadioButton cashRadioBtn;
    private javax.swing.JScrollPane cashTable;
    private javax.swing.JRadioButton chequeCashRadioBtn;
    private javax.swing.JPanel chequePayPanel;
    private javax.swing.JTable chequePayTable;
    private javax.swing.JRadioButton chequeRadioBtn;
    private javax.swing.JScrollPane chequeTable;
    private javax.swing.JLabel chqReturnLabel;
    private javax.swing.JButton closeBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JLabel grnIdLabel;
    private javax.swing.JLabel grnIdValueLabel;
    private javax.swing.JLabel headingLabel;
    private javax.swing.JPanel headingPanel;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel payTypeLabel;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JLabel statusValueLabel;
    // End of variables declaration//GEN-END:variables

}
